name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit
    permissions:
      security-events: write
      contents: read
